#coding:utf8
#
print("hello python!")
print("hello python 2!")
print("hello python 3!")
print("远程修改：hello python 4!")
print("本地修改：hello python 5!")
print("远程修改：hello python 6!")
print("本地修改：hello python 6!")
print(("本地修改：hello python 7!", 1+1))
print("远程修改：hello python 8!")
print("远程修改：hello python 9!")
print("远程修改：hello python 10!")
print("本地修改：hello python 10!")
print("远程修改：hello python 11!")
print("本地修改：hello python 11!")